### ISSUE TITLE
[v5] routine in using should provide parameter indicating whether the routine is called after a waiting

### ISSUE THREAD

**Issue by fpsqdb** [mike-marcacci/node-redlock#106]
```
await redlock.using([senderId, recipientId], 5000, async (signal, isRetry) => {
  if(isRetry) {
  // Do something...
  }

  // Do something...
  await something();

  // Make sure any necessary lock extension has not failed.
  if (signal.aborted) {
    throw signal.error;
  }

  // Do something else...
  await somethingElse();
});
```

**Comment by mike-marcacci** [comment]
Hey @fpsqdb! Out of curiosity, what's the use-case for this?

**Comment by fpsqdb** [comment]
@mike-marcacci If isRetry is true, it may indicate that the value has been modified elsewhere, and the latest value should be retrieved at this time。

**Comment by mike-marcacci** [comment]
Hi @fpsqdb, I think that would be true regardless of the value: the operation is asynchronous and the assumption is that there are many processes running across many different physical machines, hence the need for a lock in an otherwise "distributed" environment. There's nothing that would guarantee (or even suggest) that an external resource retrieved outside of a lock would not have changed by the time a lock was acquired.
