### ISSUE TITLE
Is there a way to check if lock exists?

### ISSUE THREAD

**Issue by vgoloviznin** [mike-marcacci/node-redlock#12]
Is there a way to check if any key is locked at the moment? 

Something like 

```javascript
redlock.locked(key).then(results => {
    console.log(result); //true -> locked, false -> not locked
})
```

**Comment by mike-marcacci** [comment]
Hi @vgoloviznin, there isn't at the moment. This would be trivial to implement, but I am a bit curious what exactly the the use case would be. If there's a good reason to have this feature, I'd be more than happy to implement it!

**Comment by vgoloviznin** [comment]
Hi @mike-marcacci, in fact I don't need this anymore, but the actual idea was to check the lock before doing a heavy job and notify use immediately that the request couldn't be processed. (This is not the case anymore as I've altered the architecture of the app)

**Comment by mike-marcacci** [comment]
Gotcha, thanks for explaining. Since you no longer need this I'm going to close it for now, as I wouldn't want the presence of such a feature to confuse someone who may otherwise use a pattern of "checking for a lock, then doing something that assumes there is no lock" in a way that introduces a race and goes against the idea of using locks in the first place.

For the sake of anyone else with a similar use case who finds this issue, I'd probably recommend actually attempting to acquire the lock with no retries, and then handling the error by issuing the notification that it's already locked.
