### ISSUE TITLE
Differentiate LockErrors with names/codes

### ISSUE THREAD

**Issue by ifightcrime** [mike-marcacci/node-redlock#14]
I need to handle my queue items differently depending on which type of error is thrown. For example, if I get a retry error when lock exists (#12), I'd just like to remove the queue item completely. Currently I'm just matching on the error string (https://github.com/mike-marcacci/node-redlock/blob/master/redlock.js#L309), but it would be great if each error had a different name or code associated w/ it so I could be more explicit.

If that sounds good I can PR, but wondering if you have thoughts on how they should be distinguished (name vs. code, type of code, etc.)

**Comment by mike-marcacci** [comment]
Hi @ifightcrime, I definitely don't mind further distinguishing these by more than just a message if that would help; however, I am a bit curious about your use case that would require this: redlock is able to guarantee that the any issued lock is exclusive. Currently, though, there is no mechanism for determining with certainty if another lock is issued.

For example, imagine a 3-node configuration. If 3 jobs race to the lock servers at the same time, each securing a lock on one, none will receive the lock, and will have to try again. Other scenarios – including network failures, partial deadlocks, etc – make it impossible to always establish confidence, and redlock just "assumes the worst" here. In essence, there are 3 possible situations:

1. we successfully acquired a lock
2. we did not successfully acquire a lock, and we know that it is currently acquired elsewhere
3. we did not successfully acquire a lock, and it is unclear if it is currently acquired elsewhere

Right now redlock treats 2 and 3 the same, because it's not clear to me that there is a meaningful distinction between the two, and I'm hesitant for the API to imply that there is (just because something acquired a lock doesn't mean it successfully processed its job before crashing, etc).

I mention this because, while it's perfectly acceptable to error out if a you can't acquire a lock – I do this all the time when de-duplicating a user action – if you're removing items from a queue, you run the risk of deleting messages if there is a network partition, or your redis servers go down, etc.

**Comment by ifightcrime** [comment]
Hmm yea that makes sense. I'm trying to use this as a way to dedupe duplicate sends from aws sqs. If it's a duplicate I just want to remove the duplicate sqs message. Sounds like this may not be the best way to do that? Or I could just not remove the queue item and add a check in to see if it was already processed, though the whole point was that Inwas trying to avoid an additional query.

**Comment by mike-marcacci** [comment]
Ah yes, I do understand that task, and have had to deal with that problem a couple of times. If your scale allows it, I may suggest using locks along with a more persistent "fact store" that tracks the state of each message. For example you might:

1. acquire a lock; if you are unable to acquire a lock, send your message to the back of the queue
2. once you have a lock, you *know* that nothing else is currently processing it, so it has either already been processed (successfully or otherwise), or has never been attempted; either way it's in a stable state
3. check your fact store for the presence of any facts relating to job (is it new? was it in a pending state and failed? has it already been processed?)
4. journal to the fact store as you process the message (making sure that if it crashed suddenly, it could pick up where it left off), and mark it as complete when it's done

This way, when you get a duplicate, you continue to re-queue it until it has been fully processed once and only once. In practice, keeping around a fact store for ever is unrealistic if you're dealing with any real scale, but depending on your exact case, you can probably evict facts after a "safe" amount of time – a week or two in my cases.

**Comment by mike-marcacci** [comment]
@ifightcrime - I'm going to close this issue for now, as I'm not sure there's something actionable here. Feel free to re-open it if you want!
