### ISSUE TITLE
Breaking changes of v4 explanation

### ISSUE THREAD

**Issue by andrejleitner** [mike-marcacci/node-redlock#145]
What does this actually mean?

> BREAKING: Change behavior of unlock to return an error if one or more entries cannot be removed.

**Comment by intellix** [comment]
Related: https://github.com/mike-marcacci/node-redlock/issues/65

**Comment by mike-marcacci** [comment]
To clarify, in earlier versions calling `unlock()` was always a "best attempt" with no feedback. There is typically not much you can do if you were unable to release a lock, as the most common scenarios are:

1. There is a networking issue/etc; in this case the lock will eventually expire anyhow.
2. The lock _already_ expired; you've exceeded your guarantees and so all bets are off.

The reason for changing this behavior is to highlight these cases and give the end developer the ability to detect such cases and log/alert on them. Case 2 in particular was likely the case for most users experiencing #65, where they acquired a 1s lock for a 5s expiration without ever extending it. This is a _huge_ problem in the correctness of their code, and so it's appropriate for this to throw, even if it's just going to be caught and logged.

Hopefully this helps. I'm going to close this out since I don't think there's anything actionable, but feel free to continue discussing here.

This is related to #153.
