### ISSUE TITLE
`release()` throws an error if lock already released

### ISSUE THREAD

**Issue by snird** [mike-marcacci/node-redlock#153]
The current implementation of `release()` throws an error when we try to release a lock that was already released - either by calling `release()` or simply by timing out.

the release script:
```
const RELEASE_SCRIPT = `
  local count = 0
  for i, key in ipairs(KEYS) do
    -- Only remove entries for *this* lock value.
    if redis.call("get", key) == ARGV[1] then
      redis.pcall("del", key)
      count = count + 1
    end
  end
  -- Return the number of entries removed.
  return count
`;
```

counts only succesful releases after checking that they exist.
In case the key already have been released, it won't get counted.

Then, when it returns a number less than the quorum required - it errors.

Every other script have a fallback of sort.
Shouldn't `release()` be safe to call even if the lock is already gone?
Or alternatively - returning a dedicated error for "lock already released" so we can safely catch this error alone?

**Comment by mike-marcacci** [comment]
Hi @snird, I just provided an explanation of the rationale behind this behavior [here](https://github.com/mike-marcacci/node-redlock/issues/145#issuecomment-1060017144). I'm going to go ahead and close this out, but feel free to keep discussing here if you have more thoughts/questions!

**Comment by snird** [comment]
Hi @mike-marcacci, thank you.

I read the explanation, and I think my question still stands:
If the purpose is to let the developer act, why not have a separate error for "already release" and one for "unexpected error"?

The current error scheme leaves us blind to the root cause that is knowable within the library. Wouldn't it be better to have more specific error?

**Comment by mike-marcacci** [comment]
Hi @snird,

That's a really good question with a not-quite-obvious answer. Essentially, there is no way to confidently and reliably detect the difference, and the difference is essentially meaningless. If there are 3 redis clusters, for example, there are _so many_ different potential failure states (one cluster is unreachable, one cluster that never recorded the acquired lock [only a quorum is required], one cluster that "failed over" and "forgot" the lock). Check out the [How do I check if something is locked?](https://github.com/mike-marcacci/node-redlock#how-do-i-check-if-something-is-locked) FAQ for a little more on the topic.

Even adding retry logic isn't straightforward because it's not 100% clear what guarantees it would be making. I'm definitely not opposed to it, but its goal ad logic would need to be as rigorous as those for lock acquisition.

Let me know if that helps, of if you see a useful guarantee that could be made here and that I'm missing.

**Comment by snird** [comment]
Got it.
Thank you for your patience and time @mike-marcacci !
