### ISSUE TITLE
Check if locked without acquiring a lock (in a cheap way)

### ISSUE THREAD

**Issue by jonaskello** [mike-marcacci/node-redlock#155]
My use-case is that I have a resource that have let's say 10 operations that can mutate it. The first 9 operations are lock-free and can occur in any order or simultaneously it does not matter, they modify the resource on a last write wins basis. The 10th operation is a long-running processing task (~60 seconds) and during this time none of the other 9 operations are allowed because if they change the resource the result of the processing will not be valid for the new state of the resource. So during this time any operation should be rejected which is what I want to use the lock for.

Now the way I try to go about this is to lock the resource using redlock for the 10th operation and this works well. However in all of the other 9 cases I now need to check if the resource is locked and reject the operation if it is. It is explained in the readme how to check if the resource is locked. You basically try to acquire a lock and catch the exception. However this is a very expensive way of checking for the 9 lock-free operations. They do not require a lock so basically they need to try to get the lock, and then immediately release it. So there are two thing needed to be done instead of just a cheap "peek" at the lock. Also the throwing of an exception, I think is rather expensive, at least more than returning a value to check.

Perhaps my use-case is not suited for redlock? Or is there some work-around I could use to check for lock without actually acquiring the lock?

**Comment by mike-marcacci** [comment]
Hi @jonaskello, it sounds like you might want to acquire a separate lock for each of the potentially-concurrent "steps" and then attempt to acquire all of these for the final step.

For example, lock `{resource}-step-a` on step "a" and `{resource}-step-b` on step "b" but then lock both of those in the final operation.

You definitely don't want to "peek" into locks, since that doesn't really tell you anything or make any meaningful guarantees (just because something wasn't doing something when you "peaked" doesn't prevent it from starting literally a millisecond afterwords).

I'm going to go ahead and close this issue (just for my own sanity), but feel free to keep discussing here.

**Comment by jonaskello** [comment]
@mike-marcacci Thanks for the reply :-). You are right that I do have to rethink some of the design.

One other reason for peeking at the lock that I don't know how to remove by re-design is that I have multiple GUI clients working concurrently, and only one of them should be able to change the resource at the time (hence the lock). The client should also be notified if someone else has locked the resource. So this situation occurs:

1. One GUI client sends a command to start some processing that takes about 5-20 seconds.
2. The server acquires a lock on the resource and notifies all other clients that the resource is locked.
3. A new GUI client starts up after this happens but before the processing is complete.
4. How can the new GUI client know that the resource is locked without peeking at the lock?
