### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by raelgor** [mike-marcacci/node-redlock#23]
On a simple cluster with 3 nodes created using the redis-trib.rb script, I get an "(error) MOVED" as a client error when I try to lock a resource.

Is this intended? How should these redirects be handled?

**Comment by mike-marcacci** [comment]
Hi @raelgor - sorry for the slow reply. This is likely an issue with the redis client library you're using, since Redis clusters inform the clients where a key should live by issuing MOVED responses; this leaves the routing up to the client and reduces intra-cluster traffic. If you aren't already, I'd suggest using [ioredis](https://github.com/luin/ioredis) instead of [node-redis](https://github.com/NodeRedis/node_redis), since it has built-in support for clustering. Redlock can both libraries interchangeably.

**Comment by raelgor** [comment]
Hello @mike-marcacci! Thanks for replying, I realized shortly after and used `ioredis.Cluster`, works like a charm!
