### ISSUE TITLE
How to unlock a Lock you only have the resource name?

### ISSUE THREAD

**Issue by dvergeylen** [mike-marcacci/node-redlock#30]
Thank you for this awesome module!

Is there a way to unlock / close a lock you don't have a reference to anymore but have the resource name.
For instance, what if lock a resource for a long time (15 minutes like this):
```js
function test(resource){
  redlock.lock(resource, 900000).then(function(lock) {
    // ...do something here...
    // but no unlock
  });
}
```
Then later on, how could I unlock the resource? My use case is that I have conditions to check one at a time and locking them one-by-one. If all conditions are fulfilled, I have to unlock all the gathered locks. I would prefer to avoid accumulating references to the `lock`s as my iterations are executed recursively :confused: .

**Comment by dvergeylen** [comment]
I could find a workaround :smile_cat:. But I am still interested if you have an elegant way to retrieve a lock from its resource name.

**Comment by mike-marcacci** [comment]
Hi @dvergeylen – So sorry for the slow reply here!

So, the library expects an actual instance of `Lock` for two reasons.

1. The method is actually supposed to [mutate its expiration to immediately invalidate it](https://github.com/mike-marcacci/node-redlock/blob/master/redlock.js#L159). This prevents accidentally extending a lock you are attempting to invalidate.
2. More importantly, the lock `value` is what prevents a dangerous race condition. Imagine you have 2 servers, and server A gets a lock on `SOME_RESOURCE`. Eventually, server A is done with the resource, and sends a request to redis to release the lock on `SOME_RESOURCE`. Now, due to the asynchronous nature of network requests, it's possible that the lock expires before the request reaches and is processed by redis. It's also possible that in that time, server B is able to successfully acquire a NEW lock on `SOME_RESOURCE`. If only the resource name is used in the eventually-processed "unlock" request, then it would be possible for it to prematurely release the new lock acquired by server B! To prevent this, each lock has a [cryptographically random `value`](https://github.com/mike-marcacci/node-redlock/blob/master/redlock.js#L269), to make it unique. This way, the "unlock" request from server A will only succeed if the currently-held lock is the one it's attempting to release.

All that to say, you'll almost certainly want to track at least the lock's `resource` and `value`, if you aren't able to keep a reference to the original lock.

To unlock the resource, the "most correct" way would be:

```js
const Redlock = require('redlock');

const savedLockResource = 'SOME RESOURCE';
const savedLockValue = 'xxxxxx';

lock = new Redlock.Lock(redlock, savedLockResource, savedLockValue, 1);
lock.unlock();
```

More concisely, you could get away with:

```js
redlock.unlock({ resource: 'SOME_RESOURCE', value: 'xxxxxx' });
```

Hope that helps!

**Comment by dvergeylen** [comment]
>Hope that helps!

It does! Thank you @mike-marcacci ! :+1:

**Comment by roah-chae** [comment]
@mike-marcacci 
Hello
I have the same problem, so I tried to use the unlock function after looking at this answer, but it doesn't seem to exist, so I'm asking
Is the unlock function deprecated?
If so, is there an alternative to unlock with resource key, value?
