### ISSUE TITLE
The use of EVAL prevents using node-redlock in dev/test environments

### ISSUE THREAD

**Issue by natesilva** [mike-marcacci/node-redlock#32]
We’re using `fakeredis`, but all other Redis simulators that I can find have the same limitation: they don’t support `EVAL`.

It looks like redlock is using `EVAL` to let the user replace the lock/unlock/extend commands. Would it be possible to use non-`EVAL` methods in the case where the user doesn’t choose to customize those commands? For example in logs I see this:

```
1497911517.567063 [0 127.0.0.1:58782] "eval" "return redis.call(\"set\", KEYS[1], ARGV[1], \"NX\", \"PX\", ARGV[2])" "1" "my-app:redlock:dev:testing" "4f827527f08e4379b39cec4e460b6d16" "3000"
```

That could be replaced by a plain `SET` command, which would work in `fakeredis`.

Referenced in: https://github.com/hdachev/fakeredis/issues/38

**Comment by mike-marcacci** [comment]
Hi @natesilva, this is a good question, and you are right that the lock command doesn't really need to be an EVAL. However, the unlock and extend commands really do need to, and given this, I made the lock script an eval for the sake of symmetry and maximum extensibility (since these are technically overrideable).

The reason that we need to use EVAL is because to safely release a lock, we need to atomically check the lock identity before deleting it (to make sure it is not owned by some other process). Currently, the only way to do this in redis is through lau scripts (as far as I know).

I have actually been in a similar situation myself, and would like to see EVAL added to fakeredis or a similar library. However, for my case (running automated tests) it proved to be easy enough to create new redis containers on-demand, which ultimately provides more representative results.

**Comment by natesilva** [comment]
Thank you for the detailed explanation. It does sound like setting up some test or on-demand Redis instances is the best option, and we’ll look into that.
