### ISSUE TITLE
Resource naming convention

### ISSUE THREAD

**Issue by WinMinTun** [mike-marcacci/node-redlock#36]
// the string identifier for the resource you want to lock
var resource = 'locks:account:322456';

1) Can somebody explains me the naming convention here? 'locks'? Are there other prefixes? And any significance? 
2) Is it read lock? write lock? or what kind of lock?

**Comment by mike-marcacci** [comment]
Hi @WinMinTun, there are a couple of conventions here, but none of them are necessary.

1. In redis, it's common to use colons `:` as separators, but you can use anything
2. I prefixed these examples with `locks` so that it's clear what the purpose of the key is (if somebody managing the redis server/cluster sees all these keys appearing and quickly disappearing, it's nice if they have a clue what they're doing). I also used the `locks` prefix because I didn't want to assume that the reds server is being used exclusively for locks. It would be really bad if somebody was caching the account at key `account:322456`!
4. I prefixed the account id (`322456`) with the type `account` because the IDs are auto-incremented and not globally unique.

Of course, none of these are necessary to use redlock; the only thing that really matters is that the string you pass uniquely represents the thing you're trying to lock.

**Comment by mike-marcacci** [comment]
To answer your other question, it is an *exclusive* lock. Whether you read or write is up to you!

**Comment by WinMinTun** [comment]
@mike-marcacci Thank you v much. Sorry for newbie questions, I m very new to redis and I have real-time system with a very high concurrent volume to do with Redis as main data store. I m lost currently and wish to get from you some light :D

1) is it supposed to be the key 'account:322456' to lock? why 'locks:account:322456' then? Redis key and Redlock resource different? 
2) During the lock, what would happen if other party access with GET and SET 'account:322456'? Do they have to wait or their operation fail?
3) The RedLock is the alternative to Redis Transaction? https://redis.io/topics/transactions

**Comment by mike-marcacci** [comment]
As a followup to my answer number 3 above, Redlock is certainly not something you need to use to use redis. There are MANY use cases for redis which don't require locks, and I would avoid adding this (or any other dependency) to your app if it isn't needed. If you don't have a need for ensuring system-wide exclusivity *in your business logic*, then you probably don't need to use distributed locks at all! Hopefully that makes sense! 🙂

**Comment by WinMinTun** [comment]
@mike-marcacci Thank you very much.
