### ISSUE TITLE
Using redlock in worker process

### ISSUE THREAD

**Issue by IvanMMM** [mike-marcacci/node-redlock#41]
I have Master server and several Clusters connected to it to process data. Master is locking resource and I want one cluster to unlock it once it's finished.
So, is there a way to lock resource on Master and unlock it on Worker / Cluster? Or is there a way to restore `lock` object by resource name?

**Comment by mike-marcacci** [comment]
Hey @IvanMMM, since redis is the backing store for this, that's certainly possible. However, it's probably not what you want to do. Here's why:

Before a lock is registered with redis, it generates a cryptographically random `value` to distinguishes it from any other locks that may exist. When a lock is released, it checks to make sure that the current lock in redis has this exact value, before deleting it. This is super important because there can be wide fluctuations in network speed/latency, and there is an inherent race condition between a lock's expiration and a manual call to `.release()` or `.unlock()`. For example:

1. Worker `A` acquires a lock for `foo`
2. Worker `A` attempts to release its lock for `foo`
3. Before worker `A` reaches redis, the lock expires
4. Worker `B` acquires a lock for `foo`
5. Worker `A` reaches redis, but does *not* release the worker `B`'s lock because it has a different value

If you want to force the release of a resource you can simply call:
```js
redis.del(yourResourceName)
```
Just be aware that this will delete *any* lock on that resource.

A better option would be to serialize the [`Lock`](https://github.com/mike-marcacci/node-redlock/blob/master/redlock.js#L48) and pass it to a worker.

**Comment by IvanMMM** [comment]
@mike-marcacci It could be serialized, then? That's awesome! So, I guess, just create `new Lock(...)` and use methods after it. Thank you!

**Comment by bluEEil** [comment]
@mike-marcacci Hey, I have a similar use-case where I have on process locking the resource and a different one that should unlock it.
I don't understand exactly how I can do it safely, you said I can serialize the lock and pass it to the process that needs to unlock it or pass the generated value as the resource name so I can delete it from Redis directly?

Can you provide examples for the 2 options?
