### ISSUE TITLE
Unlock(rescourceId)

### ISSUE THREAD

**Issue by iamnewspecies** [mike-marcacci/node-redlock#42]
Is there no function which directly unlocks on the basis of resourceId instead of the current function which needs an instance of Lock to unlock it.

**Comment by mike-marcacci** [comment]
Hey @iamnewspecies! This is intentional. Due to the distributed nature of these locks, it is possible for a current lock to expire and a new one to be issued between the time your “unlock” command is issued and the time it hits the redis server. To prevent the command from unlocking the wrong lock (and invalidating all the guarantees of this software), it atomicly checks that the ID is correct before unlocking.

It would be quite unsafe to remove the lock based solely on the resource name.

If you want a more in-depth discussion of the redlock algorithm check out [this article](http://redis.io/topics/distlock).

**Comment by neil-119** [comment]
In our case, our backend instances cannot directly access Redis due to a limitation of our cloud provider. So, we spun up a VM to act as a "lock manager" server - however, we need a way to pass the lock id (not just resource id) back to the client, so that the client can send a separate request to the server with the same id, reconstruct the lock object, and release the same lock, if that makes sense. Is there a way to do this apart from maybe serializing that lock object?

**Comment by Jonah246** [comment]
I have a similar issue as @neil-119.
