### ISSUE TITLE
Add ability to store data in lock "value"

### ISSUE THREAD

**Issue by lilacdev** [mike-marcacci/node-redlock#48]
Hi,

Great work !

What do you think about adding an optional argument to lock function instead of setting a random value like : 
`const lock = await redlock.lock('lock:123', 'theGuyOrServiceLocking', 1000);`

It could be useful in order to log/send an error message indicating which account is locking resource for example.

Thanks,

**Comment by mike-marcacci** [comment]
Hi @netwoof, I think that's a perfectly reasonable idea, but I'm a bit curious about your use case here. Is the goal just tagging requestor for logging, or to actually set `value` which is used in lock computations. The only valid use case I can think of for setting the latter is in deserializing the lock... which would ideally also include an expiration timestamp.

**Comment by netwoof** [comment]
For pure logging purpose, I think that almost every app knows who or what is locking a resource when a lock is requested.

My idea is much more something like "hey man (service), you are trying to modify something that is locked by man2 (another service)". We can't store this information elsewhere because lock process is internal, and I think that we need at least a multi or Lua script to store it in the same transaction used for lock.

Value could be even set in lock object and set in error when exception is thrown.

I quickly read the code, and I don't see any reason to not doing this, do you ?

Best,

**Comment by mike-marcacci** [comment]
For anyone else arriving here with a similar use case, I've [commented here](https://github.com/mike-marcacci/node-redlock/pull/49#issuecomment-466738670) about how potential misuse of this could lead to undefined behavior. One safer solution might be to allow the specification of a "prefix" for the value.

**Comment by lilacdev** [comment]
You are absolutely right, I wasn't aware of this caveat regarding Redlock algorithm. IMO, a prefix could lead to another issue, if you use : or . to add prefix, like `${prefix}:${random}`, we have to be sure that prefix does not contain those separators, or split then join except last element.

 Creating a secondary key in Lua/multi could solve it...

Anyway, this workaround (https://github.com/mike-marcacci/node-redlock/pull/49#issuecomment-466738670) is perfect atm.

Thank you !
