### ISSUE TITLE
Exceeded 10 attempts to lock the resource

### ISSUE THREAD

**Issue by bigshans** [mike-marcacci/node-redlock#67]
Here is code:
```
async function locker (lockName, timeout, callback) {
  return redlock.lock('locks:' + lockName, timeout).then(async lock => {
    let result
    try {
      result = await callback()
    }
    finally {
      await lock.unlock()
    }
    return result
  })
}

```
But I got LockError `Exceeded 10 attempts to lock the resource`. I don't know what caused it.

**Comment by bigshans** [comment]
And I can’t seem to release the lock completely

**Comment by onichandame** [comment]
I am seeing the same error. How did you solve it?

**Comment by Bluebang** [comment]
> I am seeing the same error. How did you solve it?

I am seeing the same error. did you solve it?

**Comment by onichandame** [comment]
> > I am seeing the same error. How did you solve it?
> 
> I am seeing the same error. did you solve it?

FYI, I didn't have time to investigate deeply inside the source code, so I still have no idea where the error is thrown or how it happened exactly inside redlock. But for my specific case, it was likely to be caused by [the proxy](https://github.com/RedisLabs/redis-cluster-proxy).

Here is how it happened to me. I had a cluster where each node can handle both write/read requests. A distributed lock(a.k.a redlock) cannot be acquired before more than half of the nodes have been locked. This argument requires that the client must be able to set locks explicitly on every single node in the cluster. The proxy, however, hides all the node behind it so effectively blocks the direct access from client to any node. Hence the error we see. My solution was to bypass the proxy and everything works fine then.

TBH, this error message is super useless in my case. Retries all failed, but retried for what? Please log the original error before throwing the `Exceeded 10 attempts to lock the resource` nonsense
