### ISSUE TITLE
Does this library account for keyPrefix?

### ISSUE THREAD

**Issue by ecdeveloper** [mike-marcacci/node-redlock#69]
I was wondering if redlock accounts for the `keyPrefix` passed to ioredis client instantiation. Couldn't find any references to `keyPrefix` in the codebase.

**Comment by mike-marcacci** [comment]
Hi @ecdeveloper, this doesn't do any special handling for keyPrefix so I'm not entirely sure what the behavior would be.

**Comment by ecdeveloper** [comment]
Hey @mike-marcacci, my use case is instantiating `ioredis` with different `keyPrefix` based on the environment (e.g. `app_name:dev:`, `app_name:prod`). Whenever I set a key later on, it'd account for the `keyPrefix`. For example, if I do `redis.set('content', 'some data')` - it'd set they key in redis as `app_name:dev:content`. I was wondering if you'd consider accounting fro the `keyPrefix` when locking a given key.

**Comment by arthurfranca** [comment]
`node-redis` client already auto adds prefix when using `node-redlock` both when locking and when releasing it. Looking at `ioredis` source code, it looks like it behaves the same way.

**Comment by mike-marcacci** [comment]
Just to be clear here: my understanding here is that the redis client libraries handle this transparently, so the direct answer to the question is, "no, node-redlock does not have any kind of special handling of a prefix". However, I think the answer to the real question is, "yes, you can use a prefix because the client libraries handle that transparently and node-redlock doesn't do anything to interfere with that".
